--- #YAML:1.0
name:               Net-Telnet
version:            3.04
abstract:           Interact with TELNET port or other TCP ports
author:
    - Jay Rogers <jay@rgrs.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
